// Generated by Jthereum TEST version!
pragma solidity ^0.5.2;
contract SimpleDataValue
{
	int private value;

	function setValue(int newValue) public 
	{
		value = newValue;
	}

	function getValue() public view returns (int) 
	{
		return value;
	}
}